# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          cache: true
          cache-dependency-path: "*/packages.lock.json"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      # From https://github.com/dotnet/aspire/blob/main/.github/workflows/run-tests.yml#L107
      # Mitigate "The ASP.NET Core developer certificate is not trusted. For information about trusting the ASP.NET Core developer certificate" error
      - name: Trust HTTPS development certificate (Linux)
        if: runner.os == 'Linux'
        run: dotnet dev-certs https --trust

      - name: Verify Docker is running
        # nested docker containers not supported on windows
        if: runner.os == 'Linux'
        run: docker info

      - name: Test
        run: dotnet test --no-build --verbosity normal --logger trx --results-directory ${{ github.workspace }}/test-results

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            test-results/**/*.trx
